authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'auth'

urlpatterns = [
    path('login/', authapp.LoginView.as_view(), name='login'),
    path('logout/', authapp.LogoutView.as_view(), name='logout'),
]

chatapp/urls.py
from django.urls import path

import chatapp.views as chatapp

app_name = 'main'

urlpatterns = [
    path('', chatapp.ChooseChatView.as_view(), name='choose_chat'),
    path('chat/<int:pk>/', chatapp.ChatView.as_view(), name='chat'),
    path('refresh_chats', chatapp.ChooseChatView.as_view(), name='refresh_chats'),
]

testchat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chatapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

authapp/models.py
from django.db import models


# Create your models here.

class BlurChatUser(models.Model):
    username = models.CharField(max_length=32)
    password = models.TextField()
    chat = models.ManyToManyField('chatapp.Chat')

chatapp/models.py
from django.db import models


# Create your models here.


class Chat(models.Model):
    chat_name = models.CharField(max_length=16)


class Message(models.Model):
    msg_id = models.CharField(max_length=16)
    date_client = models.CharField(max_length=16)
    time_client = models.CharField(max_length=16)
    from_user = models.CharField(max_length=16)
    text = models.TextField()
    chat_id = models.IntegerField()
    is_read = models.BooleanField(default=False)

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.forms import TextInput, EmailInput, CharField

from authapp.models import BlurChatUser


class LoginForm(AuthenticationForm):
    username = CharField(widget=TextInput(attrs={'placeholder': 'Логин', 'class': 'form-auth-field'}))
    password = CharField(widget=TextInput(attrs={'placeholder': 'Пароль', 'class': 'form-auth-field'}))

chatapp/forms.py
import django
from django.forms import TextInput, EmailInput, CharField


# from authapp.models import BlurChatUser


class CreateChatForm(django.forms.Form):
    chat_name = CharField(widget=TextInput(attrs={'placeholder': 'Введите имя чата', 'class': 'form-create-field'}))

authapp/views.py
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views import View

from django.views.generic import FormView
from authapp.forms import LoginForm


# Create your views here.

class LoginView(FormView):
    title = 'Авторизация'
    template_name = 'authapp/login.html'
    form_class = LoginForm

    def form_valid(self, form):
        username = self.request.POST['username']
        password = self.request.POST['password']
        user = auth.authenticate(username=username, password=password)
        auth.login(self.request, user)
        return redirect('main:choose_chat')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context

    def get_success_url(self):
        return reverse_lazy('main')


class LogoutView(View):
    redirect_page = 'auth:login'

    def get(self, request):
        auth.logout(request)
        return HttpResponseRedirect(reverse(self.redirect_page))

chatapp/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render

from django.views import View

from chatapp.forms import CreateChatForm
from chatapp.models import Chat, Message


class ChooseChatView(View):
    title = 'Выберите/создайте чат'
    template_name = 'chatapp/choose_chat.html'

    @staticmethod
    def is_ajax(request):
        return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

    def get(self, request):
        if not request.user.is_authenticated:
            return HttpResponseRedirect('auth/login')
        if self.is_ajax(request=request):
            Chat.objects.create(chat_name=request.GET.dict()['chat_name'])
            chats = Chat.objects.all()
            content = ''
            item = chats.last()
            content += '<a class="chat-link" href="/chat/' + str(item.id) + '/">' \
                            '<div class="chat-button">' \
                                '<div class="chat-button-text">' \
                                    '' + str(item.chat_name) + '' \
                                '</div>' \
                                '<div class="chat-button-arrow">' \
                                    '<img src="../static/img/Layer 2.svg" alt=""/>' \
                                '</div>' \
                             '</div>' \
                         '</a>'
            response = {
                'content': content
            }
            return JsonResponse(response)
        return render(request, self.template_name, {
                                                        'title': self.title,
                                                        'form': CreateChatForm,
                                                        'chats': Chat.objects.all()
                                                    })


class ChatView(View):
    template_name = 'chatapp/chat.html'

    def get(self, request, pk):
        if not request.user.is_authenticated:
            return HttpResponseRedirect('auth/login')
        chat = Chat.objects.filter(id=pk).first()
        context = {
            'title': chat.chat_name,
            'user_name': request.user.username,
            'messages': Message.objects.filter(chat_id=pk)
        }
        return render(request, self.template_name, context)

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block stylesheets %}
        {% include 'chatapp/includes/inc_stylesheets.html' %}
    {% endblock stylesheets %}
    {% block fonts %}
        {% include 'chatapp/includes/inc_fonts.html' %}
    {% endblock fonts %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="auth-page">
    <section class="main-content">
        {% block content %}
        {% endblock %}
    </section>
</body>
</html>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block title %}{{ title }} {% endblock %}
{% block content %}

<div class="auth-form-wrap">
    <h1 class="form-title-text">{{title}}</h1>
    <hr>
    <form class="login-form" method="post">
        {% csrf_token %}
        <div>
            {{ form.username }}
        </div>
        <div>
            {{ form.password }}
        </div>
        <div>
            <input class="submit-button-login" type="submit" value="Войти">
        </div>
    </form>
</div>
{% endblock %}

chatapp/templates/chatapp/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block stylesheets %}
        {% include 'chatapp/includes/inc_stylesheets.html' %}
    {% endblock stylesheets %}
    {% block fonts %}
        {% include 'chatapp/includes/inc_fonts.html' %}
    {% endblock fonts %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="chat-page">
    <section class="main-content">
        {% block content %}
        {% endblock %}
    </section>
</body>
    {% block js %}
        {% include 'chatapp/includes/inc_js.html' %}
    {% endblock %}
</html>

chatapp/templates/chatapp/chat.html
{% extends 'chatapp/base.html' %}
{% load static %}

{% block content %}

<div class="chat-wrap">
    <div class="chat-header">
        <div class="chat-title">
            {{ title }}
        </div>
        <div class="chat-persons">
            Онлайн: <span id="persons-online"></span>
        </div>
        <a href="{% url 'main:choose_chat' %}">
            <img class="exit-icon-chat" src="{% static 'img/exit.png' %}" alt="">
        </a>
    </div>
    <hr>
    <div class="write-space">
        {% if not messages %}
            <div class="separator">Сообщений пока что нет...</div>
        {% endif %}
        {% for message in messages %}
            {% ifchanged %}
                <div class="separator">{{ message.date_client }}</div>
            {% endifchanged %}
            {% if message.from_user == user_name %}
                <div id={{ message.msg_id }} class="message-box">
                    <div class="message-box-arrow-from"></div>
                    <div class="message-from-me">
                        <div class="message-text-from-me">
                            <p>
                                {{ message.text }}
                            </p>
                        </div>
                        <div>
                            <div class="message-status">
                                {% if message.is_read %}
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#EF5DA8"
                                            class="bi bi-check-all" viewBox="2 0 10 16">
                                            <path d="M8.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99
                                            4.99a.75.75 0 0 1-1.08.02L2.324 8.384a.75.75 0 1
                                             1 1.06-1.06l2.094 2.093L8.95 4.992a.252.252 0 0 1
                                                .02-.022zm-.92 5.14.92.92a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 1
                                                0-1.091-1.028L9.477 9.417l-.485-.486-.943 1.179z"></path>
                                            </svg>
                                {% else %}
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white"
                                            class="bi bi-check-all" viewBox="2 0 10 16">
                                            <path d="M8.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99
                                            4.99a.75.75 0 0 1-1.08.02L2.324 8.384a.75.75 0 1
                                             1 1.06-1.06l2.094 2.093L8.95 4.992a.252.252 0 0 1
                                                .02-.022zm-.92 5.14.92.92a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 1
                                                0-1.091-1.028L9.477 9.417l-.485-.486-.943 1.179z"></path>
                                            </svg>
                                {% endif %}
                            </div>
                            <div class="message-time from">
                                {{ message.time_client }}
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
                {% if message.is_read %}
                    <div class="message-box" id={{ message.msg_id }}>
                {% else %}
                    <div class="message-box unread" id={{ message.msg_id }}>
                {% endif %}
                    <div class="message-box-arrow-to"></div>
                    <div class="message-to-me">
                        <div class="message-username">{{ message.from_user }}</div>
                        <div class="message-text-to-me">
                            <p>
                                {{ message.text }}
                            </p>
                        </div>
                        <div class="message-time to">
                            {{ message.time_client }}
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <div class="input-block">
        <label>
            <input class="input-box" type="text" name="message-input" placeholder="Сообщение...">
        </label>
        <img class="send-message-button" src="{% static 'img/SendMsg.svg' %}" alt="">
    </div>
    <div id="username" style="display: none">{{ user_name }}</div>
</div>

{% endblock %}

chatapp/templates/chatapp/choose_chat.html
{% extends 'chatapp/base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
{% include 'chatapp/includes/inc_menu.html' %}


<div class="choose-chat-wrap">
    <h1 class="choose-chat-title-text">{{title}}</h1>
    <hr>
    <div class="chats-container">
        {% for chat in chats %}
        <a class="chat-link" href="{% url 'main:chat' chat.pk %}">
            <div class="chat-button">
                <div class="chat-button-text">
                    {{ chat.chat_name }}
                </div>
                <div class="chat-button-arrow">
                    <img src="{% static 'img/Layer 2.svg' %}" alt=""/>
                </div>
            </div>
        </a>
        {% endfor %}
        <form class="create-chat-form" method="get">
            {% csrf_token %}
            <div class="input-place">
                {{ form.chat_name }}
            </div>
            <div>
                <input id="creator" class="submit-button-create" type="submit" value="Создать">
            </div>
        </form>
    </div>
</div>
{% endblock %}

chatapp/templates/chatapp/includes/inc_fonts.html
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700&amp;subset=cyrillic" rel="stylesheet">

chatapp/templates/chatapp/includes/inc_js.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
<script src="{% static 'js/chats.js' %}"></script>
<script src="{% static 'js/websocket.js' %}"></script>

chatapp/templates/chatapp/includes/inc_menu.html
{% load static %}

<div class="exit-from-choose-chat">
    <a href="{% url 'auth:logout' %}">
        <img class="exit-icon" src="{% static 'img/exit.png' %}" alt="">
    </a>
</div>

chatapp/templates/chatapp/includes/inc_stylesheets.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">